---
- hosts: all
  become: true
  vars:
    apache_remove_default_vhost: true
    drupal_core_version: 7.x
  roles:
    - geerlingguy.drupal
    - modules
  
#    - backup-updates
    # todo: install postfix as internet site...
  tasks:
  - name: restart apache
    service: name=apache2 state=restarted
